from .test_accounts_forms import *
from .test_accounts_models import *
from .test_accounts_views import *
from .test_clear_data_dowload_products import *
from .test_integration import *
from .test_new_fonctionality import *
from .test_products_forms import *
from .test_products_views import *
from .test_products_models import *
from .test_products_apps import *
from .test_accounts_apps import *
