language: python

python:
  - '3.8.1'

before_install:
  - python -m pip install --upgrade pip
  
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:  
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip

  - unzip chromedriver_linux64.zip -d /home/travis

  - export CHROME_BIN=chromium-browser

  - psql -c 'create database purbeurre;' -U postgres

env:
  - DJANGO_SETTINGS_MODULE=purbeurreconfig.settings.travis

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test