language: python
python:
  - '3.8.1'
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database purbeurre;' -U postgres
  - psql -c 'create role Remi with password remisansfamille;' -U postgres

env:
  - DJANGO_SETTINGS_MODULE=purbeurreconfig.settings.travis

script:
  - python manage.py migrate
  - python manage.py test