language: python
python:
  - '3.8.1'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurreconfig.settings"

services:
  - postgresql

script:
  - python manage.py test