language: python
python:
  - '3.8.1'

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=purbeurreconfig.settings.travis

script:
  - python manage.py test