language: python

python:
  - '3.8.1'
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database purbeurre;' -U postgres
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3

env:
  - DJANGO_SETTINGS_MODULE=purbeurreconfig.settings.travis

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test