# Generated by Django 3.1 on 2020-11-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20201104_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateField(auto_now=True),
        ),
    ]
