# Generated by Django 3.1 on 2020-11-12 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_history'),
        ('accounts', '0006_auto_20201104_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_product', to='products.products')),
                ('remplacement_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_product', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
