# Generated by Django 3.0.7 on 2020-10-08 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categorie', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('repères_nutritionnelles_100g', models.TextField()),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('product_name_fr', models.TextField()),
                ('product_image_large', models.URLField()),
                ('product_image_small', models.URLField()),
                ('product_image_nutrition_large', models.URLField()),
                ('product_image_nutrition_small', models.URLField()),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_product', to='products.Product')),
                ('remplacement_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remplacement_product', to='products.Product')),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Store')),
            ],
            options={
                'db_table': 'product_store',
                'unique_together': {('product', 'store')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'product_category',
                'unique_together': {('product', 'categories')},
            },
        ),
    ]
