# Generated by Django 3.1 on 2020-10-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
