# Generated by Django 3.1 on 2020-10-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201028_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image_large',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image_nutrition_large',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image_nutrition_small',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image_small',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.TextField(),
        ),
    ]
