# Generated by Django 3.1 on 2020-10-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201018_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
