# Generated by Django 3.1 on 2020-10-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201028_2230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductChosed',
        ),
        migrations.DeleteModel(
            name='ProductForm',
        ),
    ]
