# Generated by Django 3.1 on 2020-10-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201018_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='category',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
